### ISSUE TITLE
Lets name all the types of trees

### ISSUE THREAD

**Issue by 9034725985** [ttpqc/Trees#1]
what are the types of trees?

**Comment by Msarker1** [comment]
mango trees?

**Comment by 9034725985** [comment]
1. Yew 
2. Pine 
3. Maple 
4. Oak 

Thanks @pratm9293

**Comment by pratm9293** [comment]
We need to divide this assignment into proper roles... but before we can do that, let's come up with different components needed.

**Comment by Msarker1** [comment]
yeah we should @pratm9293  i was thinking everyone should make one page for a a tree

**Comment by jenny0927** [comment]
we should have a group meeting to discuss about each person's role.

**Comment by jenny0927** [comment]
i want to do maple tree

**Comment by Msarker1** [comment]
I pick oak tree

**Comment by 9034725985** [comment]
pine, i pick you
